# Generated by Django 5.1.2 on 2025-03-08 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_campanha', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ItemDoado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_doacao', models.DateField()),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacoes.campanha')),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacoes.doador')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacoes.itemdoado')),
            ],
        ),
        migrations.AddField(
            model_name='campanha',
            name='doadores',
            field=models.ManyToManyField(through='doacoes.Doacao', to='doacoes.doador'),
        ),
    ]
