# Generated by Django 5.1.2 on 2025-03-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campanha',
            name='doadores',
        ),
    ]
